# Generated by Django 4.2.11 on 2024-04-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='featured_post',
            field=models.BooleanField(default=False),
        ),
    ]
