# Generated by Django 4.2.11 on 2024-04-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_featured_post_post_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
