# Generated by Django 4.2.11 on 2024-04-05 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_post_author_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='User',
            new_name='user',
        ),
    ]
