# Generated by Django 4.2.11 on 2024-04-25 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0017_comments_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comments',
        ),
        migrations.AddField(
            model_name='post',
            name='tourch',
            field=models.ManyToManyField(blank=True, default=None, related_name='comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
