# Generated by Django 4.2.11 on 2024-04-27 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0018_remove_comments_comments_post_tourch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tourch',
        ),
        migrations.AddField(
            model_name='post',
            name='comment_count',
            field=models.ManyToManyField(blank=True, default=None, related_name='comment_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
