# Generated by Django 4.2.11 on 2024-04-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_post_tourch_post_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
    ]
